# Generated by Django 5.2.8 on 2026-02-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ngoprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('otp_pending', 'OTP Pending'), ('claimed', 'Claimed'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered')], default='available', max_length=20),
        ),
    ]
