# Generated by Django 5.2.8 on 2026-02-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fooddonation_otp_code_fooddonation_otp_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='ai_trust_score',
            field=models.IntegerField(default=0),
        ),
    ]
