# Generated by Django 5.2.8 on 2026-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ngoprofile_ai_analysis_ngoprofile_ai_trust_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='ai_verified',
            field=models.BooleanField(default=False),
        ),
    ]
