# Generated by Django 5.2.8 on 2026-02-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ngoprofile_ai_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddonation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pickup',
            options={},
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered')], default='available', max_length=20),
        ),
    ]
