# Generated by Django 5.2.8 on 2026-04-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_volunteerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
